package com.utn.lab4.tpfinal.model;

public enum ProductType {
    televisores,
    cámaras_video,
    cámaras_fotográficas,
    home_theaters,
    minicomponentes,
    parlantes,
    licuadoras,
    cafeteras,
    lavarropas,
    pavas,
    eléctricas,
    cocinas,
    termotanques,
    aires_acondicionados,
    ventiladores,
    calefactores,
    colchones,
    almohadas,
    sillas,
    mesas,
    cortadora_césped,
    Notebooks,
    PC,
    monitores,
    impresoras,
    accesorio_pc,
    notebooks,
    celulares,
    tablets,
    consolas,
    Bicicletas,
    caminadores,
    carpas,
    conservadoras,
    mochilas}

